# Generated by Django 4.1.5 on 2023-03-05 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_bitch_pup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bitch',
        ),
        migrations.DeleteModel(
            name='Pup',
        ),
        migrations.AddField(
            model_name='dog',
            name='dog_sex',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
