# Generated by Django 4.1.5 on 2023-06-19 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_dog_image_dog_user_service_user_user_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='image',
            field=models.ImageField(null=True, upload_to='image'),
        ),
    ]
